/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/txToSign": {
    /**
     * Sign Transaction
     * @description Sign Transaction
     */
    post: {
      /** @description Transaction to sign */
      requestBody: {
        content: {
          "application/json": components["schemas"]["Tx"];
        };
      };
      responses: {
        /** @description Transaction ACK */
        200: {
          content: {
            "application/json": components["schemas"]["TxAck"];
          };
        };
        default: components["schemas"]["Error"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    TxAck: {
      /**
       * Format: uuid
       * @example 8c2b2b3d-fb83-497e-8138-72446b9184b6
       */
      txId: string;
    };
    Tx: {
      /**
       * Format: uuid
       * @example 8c2b2b3d-fb83-497e-8138-72446b9184b6
       */
      txId: string;
      /** @enum {string} */
      transactionType?: "TRANSFER";
      dstAddress?: string;
      signInfo?: {
          payload?: string;
          path?: number[];
        }[];
    };
    Error: {
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
